-- Public synthetic replay DDL.
-- KEY_nn/VALUE_nn names are de-identified; this is not production DDL.
-- Value columns are nullable so every deterministic generator pattern is accepted.

CREATE DATABASE IF NOT EXISTS artifact_replay
  CHARACTER SET ascii COLLATE ascii_bin;
USE artifact_replay;
CREATE TABLE artifact_replay.profile_p1 (
  `key_01` BIGINT NOT NULL,
  `value_01` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_02` BIGINT,
  `value_03` BIGINT,
  `value_04` BIGINT,
  `value_05` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_06` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_07` BIGINT,
  `value_08` DATETIME(0),
  `value_09` BIGINT,
  `value_10` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_11` DECIMAL(24,4),
  `value_12` DECIMAL(24,4),
  `value_13` DECIMAL(24,4),
  `value_14` BIGINT,
  `value_15` BIGINT,
  `value_16` BIGINT,
  `value_17` DECIMAL(24,4),
  `value_18` DECIMAL(24,4),
  `value_19` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_20` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_21` DECIMAL(24,4),
  `value_22` DECIMAL(24,4),
  `value_23` DATETIME(0),
  `value_24` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_25` DECIMAL(24,4),
  `value_26` BIGINT,
  `value_27` BIGINT,
  `value_28` BIGINT,
  `value_29` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_30` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_31` DATETIME(0),
  `value_32` DATETIME(0),
  `value_33` BIGINT,
  `value_34` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_35` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_36` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_37` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_38` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_39` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_40` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_41` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_42` BIGINT,
  `value_43` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  PRIMARY KEY (`key_01`)
) ENGINE=InnoDB;

CREATE TABLE artifact_replay.profile_p2 (
  `key_01` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `key_02` BIGINT NOT NULL,
  `key_03` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `value_01` DECIMAL(24,4),
  `value_02` BIGINT,
  `value_03` BIGINT,
  `value_04` DECIMAL(24,4),
  `value_05` DECIMAL(24,4),
  `value_06` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_07` DECIMAL(24,4),
  `value_08` DECIMAL(24,4),
  `value_09` DECIMAL(24,4),
  `value_10` DECIMAL(24,4),
  `value_11` DECIMAL(24,4),
  `value_12` DECIMAL(24,4),
  `value_13` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_14` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_15` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_16` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_17` DECIMAL(24,4),
  `value_18` DECIMAL(24,4),
  `value_19` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_20` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_21` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_22` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_23` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_24` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_25` DATETIME(0),
  `value_26` DATETIME(0),
  `value_27` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_28` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_29` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_30` DECIMAL(24,4),
  `value_31` DECIMAL(24,4),
  PRIMARY KEY (`key_01`, `key_02`, `key_03`)
) ENGINE=InnoDB;

CREATE TABLE artifact_replay.profile_p3 (
  `key_01` BIGINT NOT NULL,
  `key_03` BIGINT NOT NULL,
  `key_02` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `value_01` BIGINT,
  `value_02` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_03` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_04` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_05` BIGINT,
  `value_06` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_07` DECIMAL(24,4),
  `value_08` DECIMAL(24,4),
  `value_09` DECIMAL(24,4),
  `value_10` DECIMAL(24,4),
  `value_11` BIGINT,
  `value_12` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_13` BIGINT,
  `value_14` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_15` DATETIME(0),
  `value_16` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_17` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_18` DECIMAL(24,4),
  `value_19` DECIMAL(24,4),
  `value_20` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  `value_21` DECIMAL(24,4),
  `value_22` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin,
  PRIMARY KEY (`key_01`, `key_02`, `key_03`)
) ENGINE=InnoDB;
