package io.github.selfsizing.iblt.sidecar;

import io.github.selfsizing.iblt.core.FingerprintStore;
import io.github.selfsizing.iblt.core.IbltHash;
import io.github.selfsizing.iblt.core.IbltSketch;
import io.github.selfsizing.iblt.core.MemoryFingerprintStore;
import io.github.selfsizing.iblt.core.PkTupleCanonicalizer;
import io.github.selfsizing.iblt.core.PkTupleCanonicalizer.PkType;
import io.github.selfsizing.iblt.sql.FingerprintQuery;
import io.github.selfsizing.iblt.sql.IbltDialect;

import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * ClickHouse sidecar: over the HTTP interface ({@code java.net.http}, zero
 * third-party dependencies), implementing the same {@link IbltSidecarService}.
 *
 * <p>Why not clickhouse-jdbc: modern drivers probe {@code currentUser()} on
 * connect, which the old 2018 CH (18.16) does not support, so the connection
 * fails; the driver also carries a 23MB dependency. The HTTP interface has a
 * stable protocol and zero dependencies, a better fit for a thin
 * "sidecar reads the local database" role.</p>
 *
 * <p>The fp SQL is generated by
 * {@link io.github.selfsizing.iblt.sql.ClickHouseIbltDialect}; after the POST,
 * {@code (fp, pk)} is streamed and parsed as {@code TabSeparated}; id is still
 * computed by Java {@code cheap8}, matching the SQL Server side.</p>
 */
public final class ClickHouseHttpSidecarService implements IbltSidecarService {

    private static final Logger LOG = Logger.getLogger(ClickHouseHttpSidecarService.class.getName());

    private final HttpClient http;
    private final String baseUrl;
    private final String database;
    private final IbltDialect dialect;

    /**
     * @param baseUrl  ClickHouse HTTP endpoint, e.g. {@code http://localhost:18123}
     * @param database default database (e.g. {@code iblt_sidecar_a})
     * @param dialect  should be the ClickHouse dialect
     */
    public ClickHouseHttpSidecarService(String baseUrl, String database, IbltDialect dialect) {
        this.http = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).build();
        this.baseUrl = baseUrl;
        this.database = database;
        this.dialect = dialect;
    }

    @Override
    public BuildSketchResponse buildSketch(BuildSketchRequest request) throws Exception {
        FingerprintQuery q = request.query();
        String sql = dialect.fingerprintSql(q) + " FORMAT TabSeparated";
        PkType type = q.pkType();
        boolean lower = q.lowerForString();

        FingerprintStore store = new MemoryFingerprintStore();
        long t0 = System.nanoTime();
        long rows = 0;
        HttpResponse<Stream<String>> resp = post(sql);
        try (Stream<String> lines = resp.body()) {
            if (resp.statusCode() != 200) {
                throw new IllegalStateException("clickhouse http " + resp.statusCode() + ": "
                        + lines.collect(Collectors.joining("\n")));
            }
            Iterator<String> it = lines.iterator();
            while (it.hasNext()) {
                String line = it.next();
                int tab = line.indexOf('\t');
                if (tab < 0) {
                    continue;
                }
                long fp = Long.parseLong(line.substring(0, tab));
                String pk = line.substring(tab + 1);
                long id = IbltHash.cheap8(PkTupleCanonicalizer.encode(type, pk, lower));
                store.add(fp, id, pk);
                rows++;
            }
        }
        store.finishIngest();
        long scanMillis = Math.round((System.nanoTime() - t0) / 1e6);
        final long finalRows = rows;
        LOG.info(() -> String.format("[iblt] scan fingerprints: dialect=%s(http), rows=%d, elapsedMs=%d",
                dialect.id(), finalRows, scanMillis));

        long tb = System.nanoTime();
        IbltSketch sketch = IbltSketch.build(store, request.bucketCount(), request.hashSeed());
        long buildMillis = Math.round((System.nanoTime() - tb) / 1e6);

        SketchMetrics metrics = new SketchMetrics(rows, scanMillis, buildMillis, request.bucketCount());
        LOG.info(() -> "[iblt] sidecar(http) buildSketch done: " + metrics);
        return new BuildSketchResponse(sketch, store, metrics);
    }

    /** Re-bucket from the retained fingerprint cache (no database re-scan). */
    public IbltSketch rebucket(FingerprintStore store, int newBucketCount) throws Exception {
        return IbltSketch.build(store, newBucketCount);
    }

    @Override
    public RecheckResponse recheck(RecheckRequest request) throws Exception {
        List<String> candidatePks = request.candidatePks();
        if (candidatePks.isEmpty()) {
            return new RecheckResponse(List.of(), List.of(), 0L);
        }
        String sql = dialect.recheckSql(request.query(), candidatePks) + " FORMAT TabSeparatedWithNames";
        long t0 = System.nanoTime();
        List<String> columns = new ArrayList<>();
        List<String[]> rows = new ArrayList<>();
        HttpResponse<Stream<String>> resp = post(sql);
        try (Stream<String> lines = resp.body()) {
            if (resp.statusCode() != 200) {
                throw new IllegalStateException("clickhouse http " + resp.statusCode() + ": "
                        + lines.collect(Collectors.joining("\n")));
            }
            Iterator<String> it = lines.iterator();
            if (it.hasNext()) {
                for (String c : it.next().split("\t", -1)) {
                    columns.add(c);
                }
            }
            while (it.hasNext()) {
                rows.add(it.next().split("\t", -1));
            }
        }
        long queryMillis = Math.round((System.nanoTime() - t0) / 1e6);
        final int hit = rows.size();
        final int asked = candidatePks.size();
        LOG.info(() -> String.format("[iblt] recheck: dialect=%s(http), candidates=%d, hitRows=%d, elapsedMs=%d",
                dialect.id(), asked, hit, queryMillis));
        return new RecheckResponse(columns, rows, queryMillis);
    }

    private HttpResponse<Stream<String>> post(String sql) throws Exception {
        URI uri = URI.create(baseUrl + "/?database=" + URLEncoder.encode(database, StandardCharsets.UTF_8));
        HttpRequest req = HttpRequest.newBuilder(uri)
                .timeout(Duration.ofMinutes(5))
                .POST(HttpRequest.BodyPublishers.ofString(sql, StandardCharsets.UTF_8))
                .build();
        return http.send(req, HttpResponse.BodyHandlers.ofLines());
    }
}
